///ISO 639-2 standard (3 letters)
const Map<String, String> iso639 = {
  "aar": "Afar",
  "abk": "Abkhazian",
  "ace": "Achinese (Aceh)",
  "ach": "Acoli",
  "ada": "Adangme(One of the Ghana language)",
  "ady": "Adyghe; Adygei",
  "afa": "Afro-Asiatic (Other)",
  "afh": "Afrihili",
  "afr": "Afrikaans",
  "ain": "Ainu",
  "aka": "Akan(One of the Ghana language)",
  "akk": "Akkadian (Babylonian)",
  "alb": "Albanian",
  "ale": "Aleut (an Eskimo language from Aleutian Islands)",
  "alg": "Algonquian languages",
  "alt": "Southern Altai",
  "amh": "Amharic (or Abyssinian-main language of Ethiopia)",
  "ang": "English-Old (ca.450-1100)",
  "anp": "Angika",
  "apa": "Apache languages",
  "ara": "Arabic",
  "arc": "Aramaic (Syria)",
  "arg": "Aragonese",
  "arm": "Armenian (Hayeren)",
  "arn": "Araucanian (S.Central Chile)",
  "arp": "Arapaho",
  "art": "Artificial (Other)",
  "arw": "Arawak",
  "asm": "Assamese (Indo-Iranian sub family)",
  "ast": "Asturian-Bable-Leonese-Asturleonese",
  "ath": "Athapascan languages",
  "aus": "Australianl anguages",
  "ava": "Avaric",
  "ave": "Avestan",
  "awa": "Awadhi",
  "aym":
      "Aymara (language from indigenous people near lake Titicaca basin in Peru and Bolivia)",
  "aze": "Azerbaijani (Azeri)",
  "bad": "Banda",
  "bai": "Bamileke languages",
  "bak": "Bashkir",
  "bal": "Baluchi",
  "bam": "Bambara",
  "ban": "Balinese",
  "baq": "Basque",
  "bas": "Basa",
  "bat": "Baltic (Other)",
  "bej": "Beja (spoken near Ethiopia and ajoining regions)",
  "bel": "Belarussian (white russian)",
  "bem": "Bemba",
  "ben": "Bengali (Bangla)",
  "ber": "Berber (Other)",
  "bho": "Bhojpuri",
  "bih": "Bihari (an east indic language)",
  "bik": "Bikol",
  "bin": "Bini",
  "bis": "Bislama (one of the major Vanuatu language)",
  "bla": "Siksika (Blackfoot)",
  "bnt": "Bantu (Other)",
  "bos": "Bosnian",
  "bra": "Braj",
  "bre": "Breton (Brez)",
  "btk": "Batak (Indonesia)",
  "bua": "Buriat",
  "bug": "Buginese (Bugi)",
  "bul": "Bulgarian",
  "bur": "Burmese (Myanmasa)(belonging to the Tibeto-Burman sub family)",
  "byn": "Blin; Bilin",
  "cad": "Caddo",
  "cai": "Central American Indian (Oth.)",
  "cak": "Cakchiquel, Kaqchikel",
  "car": "Carib",
  "cat": "Catalan",
  "cau": "Caucasian (Other)",
  "ceb": "Cebuano",
  "cel": "Celtic (Other)",
  "cha": "Chamorro (Guam and Northern Mariana Islands)",
  "chb": "Chibcha (Colombia)",
  "che": "Chechen",
  "chg": "Chagatai",
  "chi": "Chinese (Zhongwen)",
  "chk": "Chuukese",
  "chm": "Mari",
  "chn": "Chinookjargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chu": "Church Slavic",
  "chv": "Chuvash",
  "chy": "Cheyenne",
  "cjs": "Shor",
  "cmc": "Chamic languages",
  "cmn": "Mandarin Dialect",
  "cnr": "Montenegrin",
  "cop": "Coptic",
  "cor": "Cornish",
  "cos": "Corsican",
  "cpe": "Creoles and pidgins-English-based (Other)",
  "cpf": "Creoles and pidgins-French-based (Other)",
  "cpp": "Creoles and pidgins-Portuguese-based (Other)",
  "cre": "Cree",
  "crh": "Crimean Tatar; Crimean Turkish",
  "crp": "Creoles and pidgins (Other)",
  "csb": "Kashubian",
  "cus": "Cushitic (Other)",
  "cze": "Czech",
  "dak": "Dakota",
  "dan": "Danish",
  "dar": "Dargwa",
  "day": "Dayak",
  "del": "Delaware",
  "den": "Slave (Athapascan)",
  "dgr": "Dogrib",
  "din": "Dinka",
  "div": "Divehi (Maldives)",
  "djc": "Dar Daju Daju",
  "doi": "Dogri",
  "dra": "Dravidian (Other)",
  "dsb": "Lower Sorbian",
  "dua": "Duala",
  "dum": "Dutch-Middle (ca.1050-1350)",
  "dut": "Dutch",
  "dyu": "Dyula",
  "dzo": "Dzongkha (Bhutani)",
  "efi": "Efik",
  "egy": "Egyptian (Ancient)",
  "eka": "Ekajuk",
  "elx": "Elamite",
  "eng": "English",
  "enm": "English-Middle (1100-1500)",
  "epo": "Esperanto",
  "est": "Estonian (Eesti)",
  "ewe": "Ewe (mainl anguage of Togo)",
  "ewo": "Ewondo",
  "fan": "Fang (Equatorial Guinea and Gabon)",
  "fao": "Faroese (Faeroese Island)",
  "fat": "Fanti (One of the Ghana language)",
  "fij": "Fijian",
  "fil": "Filipino; Pilipino",
  "fin": "Finnish (Suomi)",
  "fiu": "Finno-Ugrian (Lapland language)",
  "fng": "Fanagalo",
  "fon": "Fon (Official language of Benin with French)",
  "fre": "French",
  "frm": "French-Middle (ca.1400-1600)",
  "fro": "French-Old (ca.842-1400)",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fry": "Frisian (Frysk)",
  "ful": "Fulah (From Senegal to eastern Sudan)",
  "fur": "Friulian",
  "gaa": "Ga",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gem": "Germanic (Other)",
  "geo": "Georgian (Kartuli)",
  "ger": "German",
  "gez": "Geez(classical Ethiopic)",
  "gil": "Gilbertese (Kiribati)",
  "gla": "Gaelic (Scots)",
  "gle": "Irish",
  "glg": "Gallegan (Galician-Galego)",
  "glv": "Manx",
  "gmh": "German-Middle High (ca.1050-1500)",
  "goh": "German-Old High (ca.750-1050)",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Greek-Ancient (to1453)",
  "gre": "Greek-Modern (1453-)(Ellinika)",
  "grn": "Guarani (bolivia-paraguay-and south of Brezil)",
  "gsw": "Swiss German",
  "guj": "Gujarati (north west india)",
  "gwi": "Gwich'in",
  "hai": "Haida",
  "hat": "Haitian; Haitian Creole",
  "hau": "Hausa (Nigeria)",
  "haw": "Hawaiian",
  "haz": "Hazaragi",
  "hbs": "Serbo-Croatian",
  "heb": "Hebrew (Iwrith)",
  "her": "Herero (Namibia)",
  "hil": "Hiligaynon",
  "him": "Himachali",
  "hin": "Hindi (official language of northern India)",
  "hit": "Hittite",
  "hmn": "Hmong",
  "hmo": "HiriMotu",
  "hrv": "Croatian",
  "hsb": "Upper Sorbian",
  "hun": "Hungarian (Magyar)",
  "hup": "Hupa",
  "iba": "Iban",
  "ibo": "Igbo",
  "ice": "Icelandic",
  "ido": "Ido",
  "iii": "Sichuan Yi; Nuosu",
  "ijo": "Ijo",
  "iku": "Inuktitut",
  "ile": "Interlingue",
  "ilo": "Iloko",
  "ina": "Interlingua (International Auxilary Language Association)",
  "inc": "Indic (Other)",
  "ind": "Indonesian",
  "ine": "Indo-European (Other)",
  "inh": "Ingush",
  "ipk": "Inupiak",
  "ira": "Iranian (Other)",
  "iro": "Iroquoian languages",
  "ita": "Italian",
  "jav": "Javanese",
  "jbo": "Lojban",
  "jpn": "Japanese (Nihongo)",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "kaa": "Kara-Kalpak",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kal": "Kalaallisut(or Greenlandic)",
  "kam": "Kamba (Kenya)",
  "kan": "Kannada",
  "kar": "Karen",
  "kas": "Kashmiri",
  "kau": "Kanuri",
  "kaw": "Kawi",
  "kaz": "Kazakh",
  "kbd": "Kabardian",
  "kea": "Kabuverdianu",
  "kha": "Khasi",
  "khi": "Khoisan (Other) (Namibia and West South Africa)",
  "khm": "Khmer (Cambodian)",
  "kho": "Khotanese (or Saka-EastIranian)",
  "kik": "Kikuyu (Northern Kenya)",
  "kin": "Kinyarwanda (Rwanda)",
  "kir": "Kirghiz",
  "kls": "Kalasha",
  "kmb": "Kimbundu (Angola)",
  "kok": "Konkani (south indic)",
  "kom": "Komi",
  "kon": "Kongo",
  "kor": "Korean",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "krc": "Karachay-Balkar",
  "krl": "Karelian",
  "kro": "Kru",
  "kru": "Kurukh",
  "kua": "Kuanyama",
  "kum": "Kumyk",
  "kur": "Kurdish",
  "kut": "Kutenai",
  "lad": "Ladino",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lao": "Lao (Laothian)",
  "lat": "Latin",
  "lav": "Latvian (lettish-letonian)",
  "lbj": "Ladakhi",
  "lez": "Lezghian",
  "lim": "Limburgan; Limburger; Limburgish",
  "lin": "Lingala",
  "lit": "Lithuanian",
  "lkt": "Lakota",
  "lol": "Mongo",
  "loz": "Lozi",
  "ltz": "Letzeburgesch (luxembourg low german dialect)",
  "lua": "Luba-Lulua (Central Zaire)",
  "lub": "Luba-Katanga",
  "lug": "Ganda(or Baganda-Uganda)",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo (Kenya and Tanzania)",
  "lus": "Lushai",
  "mac": "Macedonian",
  "mad": "Madurese",
  "mag": "Magahi",
  "mah": "Marshall",
  "mai": "Maithili",
  "mak": "Makasar",
  "mal": "Malayalam",
  "man":
      "Mandingo (spoken in Sierra Leone-Liberia-Guinea-Ivory Coast-Mali and Burkina Faso)",
  "mao": "Maori",
  "map": "Austronesian (Other-Malayo-Polynesian)",
  "mar": "Marathi",
  "mas": "Masai (Nomadic people of East Africa-Kenya and Tanzania)",
  "may": "Malay",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende(Sierra Leone)",
  "mey": "Hassaniyya",
  "mga": "Irish-Middle(900-1200)",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mis": "Miscellaneous languages",
  "mkh": "Mon-Khmer (Other)",
  "mlg": "Malagasy",
  "mlt": "Maltese",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "mno": "Manobo languages",
  "moh": "Mohawk",
  "mol": "Moldavian",
  "mon": "Mongolian",
  "mos": "Mossi(More)",
  "mul": "Multiple languages",
  "mun": "Mundal anguages",
  "mus": "Creek(Muskogee)",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "myn": "Mayan languages",
  "myv": "Erzya",
  "nah": "Aztec (Nahuatl)",
  "nai": "North American Indian (Other)",
  "nap": "Neapolitan",
  "naq": "Khoekhoe, Nama (Namibia)",
  "nau": "Nauru",
  "nav": "Navajo",
  "nbl": "Ndebele-South (Zimbabwe-Botswana)",
  "nde": "Ndebele-North (Zimbabwe-Botswana)",
  "ndo": "Ndonga",
  "nds": "Low German; Low Saxon; German, Low; Saxon, Low",
  "nep": "Nepali",
  "new": "Newari",
  "nia": "Nias",
  "nic": "Niger-Kordofanian (Other)",
  "niu": "Niuean (Niue Island)",
  "nno": "Norwegian Nynorsk; Nynorsk, Norwegian",
  "nob": "Bokmål, Norwegian; Norwegian Bokmål",
  "nod": "Northern Thai",
  "nog": "Nogai",
  "non": "Norse-Old",
  "nor": "Norwegian",
  "nqo": "N'Ko",
  "nso": "Sohto-Northern",
  "nub": "Nubian languages",
  "nwc": "Classical Newari; Old Newari; Classical Nepal Bhasa",
  "nya": "Nyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oci": "Occitan (post1500)",
  "oji": "Ojibwa",
  "ori": "Oriya",
  "orm": "Oromo (Galla or Afan) (West and South Ethiopia and Kenya)",
  "osa": "Osage",
  "oss": "Ossetic",
  "ota": "Turkish-Ottoman(1500-1928)",
  "oto": "Otomian languages",
  "paa": "Papuan(Other)",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pan": "Panjabi(language of Punjab)",
  "pap": "Papiamento",
  "pau": "Palauan (Palau Island in Micronesia)",
  "peo": "Persian-Old (ca.600-400B.C.)",
  "per": "Persian (Farsi)",
  "pez": "Eastern Penan",
  "phi": "Philippine (Other)",
  "phn": "Phoenician",
  "pli": "Pali",
  "pol": "Polish",
  "pon": "Pohnpeian",
  "por": "Portuguese",
  "pra": "Prakrit languages",
  "pro": "Provencal-Old (to1500)",
  "prs": "Afghan Persian, Dari",
  "pus": "Pushto (or Pachto-Afghan)",
  "qsi": "Silent Film",
  "que": "Quechua(Bolivia-Peru and Ecuador)",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rcf": "Réunion Creole French",
  "roa": "Romance (Other)",
  "roh": "Raeto-Romance",
  "rom": "Romany(Gipsy language)",
  "rum": "Romanian",
  "run": "Rundi (or Kirundi)",
  "rup": "Aromanian; Arumanian; Macedo-Romanian",
  "rus": "Russian",
  "ruy": "Central Okinawan",
  "sad": "Sandawe",
  "sag": "Sango (Central African Republic)",
  "sah": "Yakut",
  "sai": "South American Indian (Other)",
  "sal": "Salishan languages",
  "sam": "Samaritan Aramaic",
  "san": "Sanskrit",
  "sas": "Sasak",
  "sat": "Santali",
  "scn": "Sicilian",
  "sco": "Scots",
  "sel": "Selkup",
  "sem": "Semitic (Other)",
  "sga": "Irish-Old (to900)",
  "sgn": "Sign Languages",
  "shn": "Shan",
  "sid": "Sidamo",
  "sin": "Sinhalese (Sri Lanka)",
  "sio": "Siouan languages",
  "sit": "Sino-Tibetan (Other)",
  "sla": "Slavic (Other)",
  "slo": "Slovak",
  "slv": "Slovenian",
  "sma": "Southern Sami",
  "sme": "Northern Sami",
  "smi": "Sami languages",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "smo": "Samoan",
  "sms": "Skolt Sami",
  "sna": "Shona",
  "snd": "Sindhi",
  "snk": "Soninke",
  "sog": "Sogdian",
  "som": "Somali",
  "son": "Songhai",
  "sot": "Sotho (Southern-language of The Lesotho)",
  "spa": "Spanish",
  "srd": "Sardinian",
  "srn": "Sranan Tongo",
  "srp": "Serbian",
  "srr": "Serer",
  "ssa": "Nilo-Saharan (Other)",
  "ssw": "Swati (Siswant-Siswati)",
  "suk": "Sukuma",
  "sun": "Sundanese",
  "sus": "Susu(Guinea)",
  "sux": "Sumerian",
  "swa":
      "Swahili (abantu language over much of east Africa and the Congo region)",
  "swe": "Swedish",
  "syc": "Classical Syriac",
  "syr": "Syriac",
  "tah": "Tahitian",
  "tai": "Tai (Other)",
  "tam": "Tamil (part of India and Sri Lanka)",
  "tat": "Tatar",
  "tel": "Telugu",
  "tem": "Timne",
  "ter": "Tereno",
  "tet": "Tetum",
  "tgk": "Tajik",
  "tgl": "Tagalog (Philipines)",
  "tha": "Thai",
  "tib": "Tibetan (Bodskad)",
  "tig": "Tigre",
  "tir": "Tigrinya",
  "tiv": "Tiv",
  "tkl": "Tokelau",
  "tlh": "Klingon; tlh Ingan-Hol",
  "tli": "Tlingit",
  "tmh": "Tuareg (Tamashek)",
  "tog": "Tonga (Nyasa)",
  "ton": "Tonga (Tonga Islands)",
  "tpi": "Tok Pisin",
  "tsi": "Tsimshian",
  "tsn": "Tswana (Setswana)",
  "tso": "Tsonga",
  "tuk": "Turkmen",
  "tum": "Tumbuka",
  "tup": "Tupi languages",
  "tur": "Turkish",
  "tut": "Altaic (Other)",
  "tvl": "Tuvalu",
  "twi": "Twi",
  "tyv": "Tuvinian",
  "udm": "Udmurt",
  "uga": "Ugaritic",
  "uig": "Uighur",
  "ukr": "Ukrainian",
  "umb": "Umbundu",
  "und": "Undetermined",
  "urd": "Urdu (Pakistanian)",
  "uzb": "Uzbek",
  "vai": "Vai",
  "ven": "Venda (South africa)",
  "vie": "Vietnamese",
  "vol": "Volapuk",
  "vot": "Votic",
  "wak": "Wakashan languages",
  "wal": "Walamo",
  "war": "Waray",
  "was": "Washo",
  "wel": "Welsh",
  "wen": "Sorbian languages",
  "wln": "Walloon",
  "wod": "Wolani",
  "wol": "Wolof (niger-congo language of senegambia)",
  "xal": "Kalmyk; Oirat",
  "xca": "Cantonese (Chinese dialect from Guangzhou)",
  "xch": "Chadic (spoken in Chad-northern Cameroon and northern Nigeria)",
  "xci": "Swiss Italian dialect",
  "xcs": "Caspian",
  "xho": "Xhosa(Lesotho-Bantustan-South Africa)",
  "xla": "Laz",
  "xpy": "Pygmies language",
  "xwa": "Wallon",
  "yao": "Yao",
  "yap": "Yapese",
  "yid": "Yiddish",
  "yor": "Yoruba (South West Nigeria and Benin)",
  "ypk": "Yupik languages",
  "zap": "Zapotec",
  "zbl": "Blissymbols; Blissymbolics; Bliss",
  "zen": "Zenaga",
  "zgh": "Standard Moroccan Tamazight",
  "zha": "Zhuang",
  "znd": "Zande",
  "zul": "Zulu",
  "zun": "Zuni",
  "zza": "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki",
};
